# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c0e2ffee965eb4cb7554adb21a3adea79624a3d465e684ff6eadd4ed7221c4e3e8fdc68e5434d8e4b0fb67d4578e4f9ad95628ca506fb81097ee37af1c7db3e

test:
  secret_key_base: f5e2804c42dce8dde9a0be1944e0d657eac07481475c91877989d5ceaa474fc671d0cdff373d4dcfc1420f7eb5e13fdf964eb4730799a795bbf72b12df9a70cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
